"""System constants for Trading System v2.0"""

# Instrument tokens (NSE)
NIFTY_TOKEN = 256265
BANKNIFTY_TOKEN = 260105
INDIA_VIX_TOKEN = 264969

# Exchange codes
NSE = "NSE"
NFO = "NFO"
MCX = "MCX"

# Trading hours (IST)
MARKET_OPEN_HOUR = 9
MARKET_OPEN_MINUTE = 15
MARKET_CLOSE_HOUR = 15
MARKET_CLOSE_MINUTE = 30

# Entry window
ENTRY_START_HOUR = 10
ENTRY_START_MINUTE = 0
ENTRY_END_HOUR = 15
ENTRY_END_MINUTE = 0

# Intraday exit
INTRADAY_EXIT_HOUR = 15
INTRADAY_EXIT_MINUTE = 15

# Data intervals
INTERVAL_5MIN = "5minute"
INTERVAL_15MIN = "15minute"
INTERVAL_DAY = "day"

# Lookback periods
REGIME_LOOKBACK_DAYS = 20
IV_PERCENTILE_LOOKBACK = 252  # 1 year of trading days
CORRELATION_LOOKBACK = 20

# Order types
ORDER_TYPE_MARKET = "MARKET"
ORDER_TYPE_LIMIT = "LIMIT"
ORDER_TYPE_SL = "SL"
ORDER_TYPE_SLM = "SL-M"

# Transaction types
BUY = "BUY"
SELL = "SELL"

# Product types
PRODUCT_MIS = "MIS"  # Intraday
PRODUCT_NRML = "NRML"  # Overnight

# Position status
STATUS_OPEN = "OPEN"
STATUS_CLOSED = "CLOSED"
STATUS_PENDING = "PENDING"

# Exit reasons
EXIT_PROFIT_TARGET = "PROFIT_TARGET"
EXIT_STOP_LOSS = "STOP_LOSS"
EXIT_TIME_BASED = "TIME_BASED"
EXIT_EOD = "EOD"
EXIT_REGIME_CHANGE = "REGIME_CHANGE"
EXIT_CIRCUIT_BREAKER = "CIRCUIT_BREAKER"
EXIT_MANUAL = "MANUAL"
