"""add_margin_used_to_broker_positions

Revision ID: ff623aa1e0db
Revises: 20260212_trailing_stop
Create Date: 2026-02-13 15:01:26.530350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff623aa1e0db'
down_revision: Union[str, None] = '20260212_trailing_stop'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broker_positions', sa.Column('margin_used', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
